### ISSUE TITLE
Get rid of async code in BaseContaner's constructor

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1253]
We run async code in BaseContaner's constructor which isn't good, and actually not possible with async/await. We need to figure out how to re-write it in async way. This error is thrown:

```
(node:15010) UnhandledPromiseRejectionWarning: TimeoutError: Timed out waiting for element with css selector of '.plans-features-main__group' to be present and displayed
Wait timed out after 40821ms
    at /Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at ManagedPromise.invokeCallback_ (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: Timed out waiting for element with css selector of '.plans-features-main__group' to be present and displayed
    at scheduleWait (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at Driver.wait (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at Object.waitTillPresentAndDisplayed (/Developer/a8c/wp-e2e-tests/lib/driver-helper.js:106:16)
    at PickAPlanPage.waitForPage (/Developer/a8c/wp-e2e-tests/lib/base-container.js:50:29)
    at new BaseContainer (/Developer/a8c/wp-e2e-tests/lib/base-container.js:28:8)
    at new PickAPlanPage (/Developer/a8c/wp-e2e-tests/lib/pages/signup/pick-a-plan-page.js:13:3)
    at Context.<anonymous> (/Developer/a8c/wp-e2e-tests/specs-jetpack-calypso/wp-jetpack-connect-spec.js:145:25)
    at runTest (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/testing/index.js:163:22)
    at /Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/testing/index.js:184:16
    at new ManagedPromise (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at controlFlowExecute (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/testing/index.js:183:14)
    at TaskQueue.execute_ (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /Developer/a8c/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
(node:15010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by brbrr** [comment]
Hey @Stojdza. Could you please take a quick look? Is there an easy way to fix this?

**Comment by Stojdza** [comment]
@brbrr Does test fail because of this error? Some of this errors are expected for now, especially for Woo and Jetpack.
In BaseContainer constructor we are using async functions, but we don't have async/await. Do you have any idea how else we can do this?

**Comment by Stojdza** [comment]
> When an async function is called, it returns a Promise. When the async function returns a value, the Promise will be resolved with the returned value.

So, yes, page object will be returned. And tests are passing, I would say it's ok :)
