### ISSUE TITLE
Fix Payment Button Test throws warning about promises

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1366]
```
Insert a payment button: @parallel @jetpack @visdiff
      ✓ Can log in (11076ms)
      ✓ Can insert the payment button (7236ms)
      ✓ Can see the payment button inserted into the visual editor (8581ms)
      ✓ Can publish and view content (18210ms)
      ✓ Can see the payment button in our published post (63ms)
      ✓ The payment button in our published post opens a new Paypal window for payment (7208ms)
(node:35830) UnhandledPromiseRejectionWarning: Error: EPIPE write EPIPE
    at ClientRequest.<anonymous> (/Users/alisterscott/Projects/a8c/wp-e2e-tests/node_modules/selenium-webdriver/http/index.js:238:15)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:605:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite (net.js:837:10)
(node:35830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alisterscott** [comment]
I can't readily reproduce this one 👎
