### ISSUE TITLE
Selenium addCookie function update

### ISSUE THREAD

**Issue by chenchaoyi** [Automattic/wp-e2e-tests#452]
The current specs-i18n tests are broken, and it seems due to selenium 3 `addCookie` function breaking change.

```  1) WordPress.com Sign Up Can Create A Free Blog (zh-cn) Desktop:
     TypeError: addCookie called with non-cookie parameter
      at TypeError (native)
      at Options.addCookie (node_modules/selenium-webdriver/lib/webdriver.js:1225:13)
      at WPHomePage.setRegularView (lib/pages/wp-home-page.js:17:24)
      at new WPHomePage (lib/pages/wp-home-page.js:11:9)
      at SignUpFlow.createFreeBlogWithScreenshots (lib/flows/signup-flow.js:60:22)
      at Context.<anonymous> (specs-i18n/wp-signup-i18n-zh-cn-spec.js:28:14)
      at runTest (node_modules/selenium-webdriver/testing/index.js:164:22)
      at node_modules/selenium-webdriver/testing/index.js:185:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1085:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:184:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3075:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2982:25)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
  From: Task: WordPress.com Sign Up Can Create A Free Blog (zh-cn) Desktop
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:183:10)
      at node_modules/selenium-webdriver/testing/index.js:102:5
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1384:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3075:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2935:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
```

**Comment by alisterscott** [comment]
Closed by #453
