### ISSUE TITLE
Executing authentication specs against calypso.live fails

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#943]
When executing authentication specs against calypso.live (dserve), for example:

` ./run.sh -g -b test/d-serve-full-suite -u https://calypso.live`

Most of the magic link tests open wordpress.com anyway, even if requested from another environment like calypso.live, so is there any point having these execute against calypso.live?

If there's no point, I'm thinking when passing in `-b` we could ignore the authentication specs?

What do you think @Automattic/flowpatrol  @Tug ?

output:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Failed Test: [WPCOM] Authentication: (mobile) @parallel @jetpack @visdiff @chrome 
 # attempts: 2
     output: 
22:16:36 Magellan child process start

22:16:42   [WPCOM] Authentication: (mobile) @parallel @jetpack @visdiff
22:16:42     Logging In and Out:
22:16:42       Can Log In
        ✓ Can log in (16977ms)
        ✓ Can see Reader Page after logging in (1685ms)
22:17:01       Can Log Out
        ✓ Can view profile to log out (332ms)
22:17:07         ✓ Can logout from profile page (5420ms)
22:17:07         ✓ Can see wordpress.com home when after logging out (124ms)
22:17:07     Can Log in on a 2fa account
22:17:23       ✓ Should be on the /log-in/sms page (52ms)
22:17:30       ✓ Enter the 2fa code and we're logged in (7134ms)
22:17:30     Can Log in on a 2fa account
22:17:47       ✓ Should be on the /log-in/authenticator page
      ✓ Enter the 2fa code and we're logged in (6905ms)
22:17:54     Can Log in on a passwordless account
22:17:55       Can request a magic link email by entering the email of an account which does not have a password defined
        ✓ Can find the magic link in the email received (2408ms)
22:18:05         Can use the magic link to log in
22:18:28           1) Visit the magic link and we're logged in
22:18:28 FAILED: Taking screenshot of: 'https://wordpress.com/'
22:18:29     Can Log in on a passwordless account with 2fa using sms
22:18:29       Can request a magic link email by entering the email of an account which does not have a password defined
22:18:41         ✓ Can find the magic link in the email received (2283ms)
22:18:41         Can use the magic link and the code received via sms to log in
22:18:46           2) "before all" hook: ret
22:18:47     Can Log in on a passwordless account with 2fa using authenticator
22:18:48       Can request a magic link email by entering the email of an account which does not have a password defined
22:18:58         ✓ Can find the magic link in the email received (2451ms)
22:18:58         Can use the magic link and the code received via sms to log in
22:19:05           ✓ Should be on the /log-in/authenticator page
22:19:11           ✓ Enter the 2fa code and we're logged in (5431ms)
22:19:14   14 passing (undefinedms)
22:19:14   2 failing
22:19:14   1) [WPCOM] Authentication: (mobile) @parallel @jetpack @visdiff Can Log in on a passwordless account Can request a magic link email by entering the email of an account which does not have a password defined Can use the magic link to log in Visit the magic link and we're logged in:
22:19:14      TimeoutError: Timed out waiting for element with css selector of '.magic-login__handle-link' to be present and displayed
22:19:14 Wait timed out after 20811ms
22:19:14       at node_modules/selenium-webdriver/lib/promise.js:2201:17
22:19:14       at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
22:19:14       at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
22:19:14       at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
22:19:14       at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
22:19:14       at node_modules/selenium-webdriver/lib/promise.js:668:7
22:19:14       at <anonymous>
22:19:14       at process._tickCallback (internal/process/next_tick.js:188:7)
22:19:14   From: Task: Timed out waiting for element with css selector of '.magic-login__handle-link' to be present and displayed
22:19:14       at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
22:19:14       at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
22:19:14       at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
22:19:14       at Object.waitTillPresentAndDisplayed (lib/driver-helper.js:64:16)
22:19:14       at MagicLoginPage.waitForPage (lib/base-container.js:39:23)
22:19:14       at MagicLoginPage.BaseContainer (lib/base-container.js:20:8)
22:19:14       at new MagicLoginPage (lib/pages/magic-login-page.js:6:24)
22:19:14       at Context.<anonymous> (specs/wp-log-in-out-spec.js:235:24)
22:19:14       at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
22:19:14       at node_modules/selenium-webdriver/testing/index.js:184:16
22:19:14       at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
22:19:14       at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
22:19:14       at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
22:19:14       at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
22:19:14       at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
22:19:14       at node_modules/selenium-webdriver/lib/promise.js:668:7
22:19:14       at <anonymous>
22:19:14   From: Task: [WPCOM] Authentication: (mobile) @parallel @jetpack @visdiff Can Log in on a passwordless account Can request a magic link email by entering the email of an account which does not have a password defined Can use the magic link to log in Visit the magic link and we're logged in
22:19:14       at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
22:19:14   2) [WPCOM] Authentication: (mobile) @parallel @jetpack @visdiff Can Log in on a passwordless account with 2fa using sms Can request a magic link email by entering the email of an account which does not have a password defined Can use the magic link and the code received via sms to log in "before all" hook: ret:
22:19:14      Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".magic-login__handle-link button.is-primary"}
22:19:14   (Session info: chrome=54.0.2840.100)
22:19:14   (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-141-generic x86_64)
22:19:14       at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
22:19:14       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
22:19:14       at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
22:19:14       at <anonymous>
22:19:14       at process._tickCallback (internal/process/next_tick.js:188:7)
22:19:14   From: Task: WebDriver.findElement(By(css selector, .magic-login__handle-link button.is-primary))
22:19:14       at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
22:19:14       at thenableWebDriverProxy.findElement (node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
22:19:14       at Object.highlightElement (lib/driver-helper.js:21:27)
22:19:14       at Object.clickWhenClickable (lib/driver-helper.js:31:7)
22:19:14       at MagicLoginPage.finishLogin (lib/pages/magic-login-page.js:11:23)
22:19:14       at EventEmitter.<anonymous> (specs/wp-log-in-out-spec.js:293:23)
22:19:14       at Client.EventEmitter.(anonymous function) [as emit] (node_modules/@xmpp/events/lib/EventEmitter.js:46:24)
22:19:14       at EventEmitter.<anonymous> (lib/xmpp-client.js:18:11)
22:19:14       at Client.EventEmitter.(anonymous function) [as emit] (node_modules/@xmpp/events/lib/EventEmitter.js:46:24)
22:19:14       at Parser.listeners.element.element (node_modules/@xmpp/connection/index.js:118:12)
22:19:14       at Parser.onEndElement (node_modules/@xmpp/xml/lib/Parser.js:54:12)
22:19:14       at SaxLtx.Parser.parser.on.name (node_modules/@xmpp/xml/lib/Parser.js:33:14)
22:19:14       at SaxLtx._handleTagOpening (node_modules/ltx/lib/parsers/ltx.js:35:14)
22:19:14       at SaxLtx.write (node_modules/ltx/lib/parsers/ltx.js:127:18)
22:19:14       at Parser.write (node_modules/@xmpp/xml/lib/Parser.js:67:17)
22:19:14       at TLSSocket.listeners.data.data (node_modules/@xmpp/connection/index.js:68:19)
22:19:14       at addChunk (_stream_readable.js:263:12)
22:19:14       at readableAddChunk (_stream_readable.js:250:11)
22:19:14       at TLSSocket.Readable.push (_stream_readable.js:208:10)
22:19:14       at TLSWrap.onread (net.js:594:20)
```

**Comment by hoverduck** [comment]
Can we replace `wordpress.com` with `${calypsoBaseURL}` in the magic links like we do with the invite links?

If that doesn't work I agree with just skipping the tests if the `liveBranch` config value is true, at least for now.  We could log an issue with dserve or wp-calypso to try and get it working in the future and turn those tests back on.

**Comment by alisterscott** [comment]
> Can we replace wordpress.com with ${calypsoBaseURL} in the magic links like we do with the invite links?

No, I'd already tried this and it doesn't work unfortunately. There's a built in signature for security reasons so tampering with the URLs causes this error:

<img width="387" alt="screen shot 2018-02-16 at 11 32 04 am" src="https://user-images.githubusercontent.com/128826/36289696-1ffad8da-130d-11e8-8fe3-92811c5aee1c.png">

> If that doesn't work I agree with just skipping the tests if the liveBranch config value is true, at least for now. We could log an issue with dserve or wp-calypso to try and get it working in the future and turn those tests back on.

Cool, I'll do that
